title : Tushar Bansal
logo : assets/headshot_circle.jpg
description : Hi, Welcome to my portfolio! I am currently a Data Science grad student at UT Austin and an Operations Research Intern at Dematic. In my free time, I like to listen to music, go to the gym or read about current affairs. I am looking to leverage my skills and experience in a role that optimizes operations and/or builds machine learning algorithms.
show_downloads : false
theme : jekyll-theme-minimal
